site_name: VergeRunner
copyright: "&copy; 2024 TakahiroNishigaki"
theme:
  name: material
  palette:
    media: "(prefers-color-scheme: dark)"
    scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to system preference
    accent: teal
    primary: teal
markdown_extensions:
  - tables
  - admonition
nav:
  - Home: index.md
  - インストールと認証について: setup.md
  - 機能紹介: functions.md
  - マニュアル:
    - Alarmの設定: manual\manual_alarm.md
    - BreakEvenの設定: manual\break_even.md
    - 割合決済の設定: manual\ratio_exit.md
    - Fibo編集: manual\edit_fib.md
    - チャートテンプレートの保存: manual\save_chart_template.md
  - ホットキー: hotkeys.md
  - ReleaseNote:
    - v1.2.0: release_note/rn_v1.2.0.md
  - ヘルプ: help.md
plugins:
extra_css:
  - css/style.css