site_name: VergeRunner
copyright: "&copy; 2024 TakahiroNishigaki"
theme:
  name: material
  palette:
    media: "(prefers-color-scheme: dark)"
    scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to system preference
    accent: teal
    primary: teal
markdown_extensions:
  - tables
  - admonition
nav:
  - Home: index.md
  - クイックスタート:
    - インストール: how_to_install.md
    - ライセンス認証: activation.md
  - 機能紹介: functions.md
  - マニュアル:
    - Alarmの設定: manual\manual_alert.md
    - Fibo編集: edit_fib.md
  - ホットキー: hotkeys.md
  - ReleaseNote:
    - v1.2.0: release_note/rn_v1.2.0.md
    # - v1.3.0:
  - トラブルシュート: troubleshooting.md
plugins:
extra_css:
  - css/style.css