site_name: VergeRunner
theme:
  name: material
  palette:
    media: "(prefers-color-scheme: dark)"
    scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to system preference
    accent: teal
    primary: teal

nav:
  - Home: index.md
  - 機能一覧: functions.md
  - インストール方法: how_to_install.md
  - 使用方法: how_to_use.md
  - ホットキー: hotkeys.md
markdown_extensions:
  - tables